pluginManagement {
    repositories {
        maven { url = 'https://mirrors.cloud.tencent.com/nexus/repository/gradle-plugins/' }
        maven { url = 'https://mirrors.cloud.tencent.com/nexus/repository/maven-public/' }
        gradlePluginPortal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}
